### ISSUE TITLE
port 8047

### ISSUE THREAD

**Issue by thbeh** [hrbrmstr/sergeant#11]
Hi, I am testing sergeant against MapR cluster and to my knowledge we should either be using 31010 or zk port and 8047 is drillbits management page in MapR.

It looks like using sergeant it cannot use 31010 but only 8047. Is this correct?

**Comment by hrbrmstr** [comment]
I can make that configurable. I use open source versions and it hasn't failed me yet but I'll tweak it later this week.

**Comment by thbeh** [comment]
Thanks.
