### ISSUE TITLE
sergeant errors and warnings keeps popping even after removing it

### ISSUE THREAD

**Issue by sanjmeh** [hrbrmstr/sergeant#12]
I had installed the sergeant package but could not figure out how to use it. 
Meanwhile, strange errors started appearing mostly when I am inside the debugger and press Q. I used to get sergeant package related errors. Even though I had nothing (no code) on sergeant in my source file. So I decided to uninstall it. 

Even after uninstalling the package following warning comes on sourcing my R file.

```
Warning message:
In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  there is no package called ‘sergeant’
```

And to top it now on entering the Q command in the Rstudio debugger the sergeant package is loaded - twice. Where is the package coming from? And how is it called by just the Q command?

**Comment by hrbrmstr** [comment]
I have no access to your system, have no idea how you manage it or manage R packages. It sounds like you crazily have auto-workspace saving turned on and shld disable that. But, this issue has absolutely nothing to do with the `sergeant` package so I'm closing it.

Also `sergeant` *requires* Apache Drill and my documentation was more than sufficient to get it running for anyone using Apache Drill and R.
