### ISSUE TITLE
Support for authentication in drill_connection

### ISSUE THREAD

**Issue by Ahine** [hrbrmstr/sergeant#16]
Hi! I read in your README that sergeant tools were not designed with authentication/encryption in mind due to the lack of need for support. We have been using sergeant at my work to run drill queries against our hdfs for a while, and are currently in the process of migrating to a new drill endpoint that requires authentication. We would love to continue using the sergeant library to run these queries, so if you have the ability to implement authentication we would greatly appreciate it!

**Comment by hrbrmstr** [comment]
Thx for using the pkg and filing an issue!

Ah, I was anticipating this day. I knew it would come eventually.

I'll setup a Docker image and start work in this pronto. I totally understand the need for this in a real production environment and it shouldn't be too difficult.

**Comment by hrbrmstr** [comment]
Just pushed up a commit that seems to work, but I also failed to ask the context for auth.

The commit enables auth on the REST API and is currently aligned with the DBI interface (which means it also works with the `dplyr`/`dbplyr` interface).

Pls give it a go when you have time.

**Comment by Ahine** [comment]
Hi,

Just gave it a go in our production environment. Ran into an error where the POST response isn't JSON, but rather an html document. Seems like the drill_query returned the html page for 'Invalid username or password' rather than an expected JSON object. This is strange to me because our 'authentication' is pretty loose, and currently we only receive the 'invalid username/password' response on our drill web console when the fields are empty.

This is what the code I'm attempting to run looks like

`fetch_with_drill <- function(query) {
  dc <- drill_connection(host = Sys.getenv("DRILL_HOST", "(our drill client)"),
                         port = Sys.getenv("DRILL_PORT", 8047),
                         user = Sys.getenv("DRILL_USER", "username"),
                         pass = Sys.getenv("DRILL_PASSWORD", "password"),
                         ssl = TRUE)
  
  result <- drill_query(dc, query)
  
  return(result)
}`

When I debug it appears that the username and password fields are making it to the drill connection object just fine, but are getting lost somewhere in authentication. I can't tell where, though.

**Comment by hrbrmstr** [comment]
OH. My apologies. I don't think I covered this bit, just the DBI/dplyr.

Posting a fix in like 30m. 

Many, many thanks for the bug report.

**Comment by Ahine** [comment]
I toyed with it and after fixing a small variable naming error (passing username into auth_drill when user was the correct variable name) it worked! I created a pull request for the small correction. Thank you for being so responsive and working on this package!
