### ISSUE TITLE
BREAKING STUFF: 0.7.0 re-introducts JDBC dependency

### ISSUE THREAD

**Issue by hrbrmstr** [hrbrmstr/sergeant#20]
Hopefully if you are running into issues with this, you'll see this issue and add your comments here.

Sufficient interest in moving the JDBC bits to a sibling pkg will cause that to happen.

**Comment by cboettig** [comment]
Officially casting my vote for making anything that re-introduces rJava dependency going into a sibling package.  (I had no idea that installing rJava on a mac could be harder than on linux!)

@jennybc will back me up on avoiding rJava-dependent packages in the classroom, and I'd love to introduce students to drill one of these days...

**Comment by hrbrmstr** [comment]
done https://github.com/hrbrmstr/sergeant-caffeinated

**Comment by cboettig** [comment]
👏 This makes me very happy.  And great name, as always 🎩
