### ISSUE TITLE
Problem with installing sergeant

### ISSUE THREAD

**Issue by hermandr** [hrbrmstr/sergeant#21]
Hi,

I am encountering problems in installing sergeant.

Upon installing 
```
devtools::install_github("hrbrmstr/sergeant")
```
I am getting the error below:
Error: package or namespace load failed for 'sergeant':
 .onLoad failed in loadNamespace() for 'rJava', details:
  call: inDL(x, as.logical(local), as.logical(now), ...)
  error: unable to load shared object 'C:/Users/herma/Documents/R/win-library/3.5/rJava/libs/i386/rJava.dll':
  LoadLibrary failure:  %1 is not a valid Win32 application.

Error: loading failed
Execution halted
*** arch - x64
ERROR: loading failed for 'i386'
* removing 'C:/Users/herma/Documents/R/win-library/3.5/sergeant'
In R CMD INSTALL

-------------------
version output:
platform       x86_64-w64-mingw32          
arch           x86_64                      
os             mingw32                     
system         x86_64, mingw32             
status                                     
major          3                           
minor          5.0                         
year           2018                        
month          04                          
day            23                          
svn rev        74626                       
language       R                           
version.string R version 3.5.0 (2018-04-23)
nickname       Joy in Playing

**Comment by hermandr** [comment]
I installed using
install.packages("sergeant")
It went well.

Thanks

**Comment by hrbrmstr** [comment]
the CRAN version has no rJava dependency. The development version and possible future CRAN version does. What you are getting via CRAN is a much older version of the package.
