### ISSUE TITLE
Support dbQuoteIdentifier method for `src_drill` class

### ISSUE THREAD

**Issue by davidski** [hrbrmstr/sergeant#31]
> Tested under 0.8.0 branch

It looks like the `src_drill()` class doesn't support the `dbQuoteIdentifier()` method. This keeps the super nifty `glue::glue_sql()` function from being as useful as it could be.

``` r
library(sergeant)
con <- src_drill()

fields_to_select <- c("first_name", "last_name")

glue::glue_sql("SELECT {`fields_to_select`*} FROM cp.`employee.json` LIMIT 20", .con = con)
#> Error in (function (classes, fdef, mtable) : unable to find an inherited method for function 'dbQuoteIdentifier' for signature '"src_drill", "character"'
```

<sup>Created on 2019-01-10 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by hrbrmstr** [comment]
#ty

**Comment by davidski** [comment]
Doh! I clearly didn't understand what `src_drill()` was doing -- wrapping the `dbConnect()` and `src_sql()` [now [deprecated](https://dbplyr.tidyverse.org/reference/src_sql.html), BTW]) calls.

Thanks for the investigation and feedback!
