### ISSUE TITLE
Improve drill_up() interactive experience

### ISSUE THREAD

**Issue by davidski** [hrbrmstr/sergeant#33]
I'm thinking through how the `drill_up()` interactive experience could be made a bit easier. That function returns a `stevedore` object, which the user is responsible for terminating (as it says in the fine documentation :wink:). If the user doesn't capture the stevedore object coming back from the `drill_up()` call, they have to `get()` and then `stop()` the container manually, which could be further complicated if they also failed to capture the container ID from the `drill_up()` call.

Any thoughts on the best way of documenting a virtuous workflow? Can't protect the user completely here, but I want to make it a bit clearer if a user don't have previous experience with stevedore. Perhaps a more verbose message when `drill_up()` is in interactive mode? A vignette? (To be clear, I'm considering writing the PR myself...not just adding things to your queue!)

> This may or may not be motivated by this author's first stumblings through the stevedore interface. 😜

**Comment by hrbrmstr** [comment]
Lemme know if the new `showall_drill()`, `killall_drill()` and `drill_down()` ease this pain a bit :-)

I have a `killall_splash()` function in the `splashr` package that i just riffed off for this.

Also, if you could/don't have an objection to clone the 0.8.0 branch and add yourself as a contributor in the Authors@R section it would be most appreciated. This testing and feedback has been invaluable!

**Comment by hrbrmstr** [comment]
Having said ^^ if you could also ensure you've got PGP keys setup for signing commits that'd be 👍 as well. It's not required but it helps me keep track of project integrity.

**Comment by davidski** [comment]
Definitely! I've run with verified commits for a while now. :) <Cue discussion on the challenges with getting signed releases on CRAN, what with the changes CRAN sometimes makes in packages sources.>
