### ISSUE TITLE
build_sql moved from dplyr to dbplyr

### ISSUE THREAD

**Issue by alistaire47** [hrbrmstr/sergeant#5]
Hi! I saw your posts about this on Twitter and it looked really cool, so I though I'd try it out. However, that involved another bout in the battle to get rJava to compile from source (which I appear to have won this time!), which led me to a sergeant installation error that

> Error : object ‘build_sql’ is not exported by 'namespace:dplyr'

which is true for devel-dplyr, as it's been moved to [dbplyr](https://github.com/tidyverse/dbplyr). (It's actually the case for most of the database-focused dplyr imports; `build_sql` is just the first it runs into.) Reinstalling CRAN-dplyr allows sergeant to be installed, but it still can't be used with devel-dplyr, which is a shame, as the update contains a lot of useful features.

According to [the blog post about the dplyr 0.6 release candidate](https://blog.rstudio.org/2017/04/13/dplyr-0-6-0-coming-soon/), it was to be submitted to CRAN yesterday. I'm not sure if that happened or quite when it will arrive on the mirrors, but for sergeant to be used at that point `sergeant/R/sergeant-package.r` will need to point to dbplyr. 

If you want to update it now, I'm happy to make a PR if you want, though it's not a very complicated change, really.

**Comment by hrbrmstr** [comment]
PR & adding yourself to DESCRIPTION as ctb wld be super helpful. Checking
the pkg out and taking time to file an issue is very much appreciated.
