### ISSUE TITLE
Does sergeant really need Java?

### ISSUE THREAD

**Issue by psychemedia** [hrbrmstr/sergeant#7]
Hi

I'm [running Apache Drill in a docker container linked to a rocker/tidyverse container](https://blog.ouseful.info/2017/06/16/rolling-your-own-jupyter-and-rstudio-data-analysis-environment-around-apache-drill-using-docker-compose/), which doesn't include Java.

Is there any reason why you use RJDBC rather than DBI?

**Comment by hrbrmstr** [comment]
It's a rly good question with a short answer of "yes" but a long answer of
"it shouldn't".

The first stab at the pkg was w/o dplyr integration and was just a RJDBC
wrapper pkg with some extra Drill stuff tossed in. However, the dplyr
interface is 100% DBI REST so I can definitely refactor the pkg a bit to
make RJDBC/rJava optional by doing an internal namespace existence test and
a more dynamic require if folks end up reverting to RJDBC (I do on occasion
when I get a large SQL statement from one of the python folks at work that
I don't try to translate to dplyr syntax immediately). I also used to
include the drill jdbc jar. Lemme see if I can do the refactoring today or
tomorrow as it's a ++gd idea/request and will make the pkg a bit less
heavyweight.

**Comment by cgivre** [comment]
+1 on that…

**Comment by hrbrmstr** [comment]
give 0.5.0 a go. I think I managed to successfully auto-decouple rJava & RJDBC but I don't have time to test in a docker container at the moment.

**Comment by psychemedia** [comment]
Installing w/ `devtools::install_github("hrbrmstr/sergeant")` gives:

````
...
** preparing package for lazy loading
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  there is no package called ‘RJDBC’
ERROR: lazy loading failed for package ‘sergeant’
* removing ‘/usr/local/lib/R/site-library/sergeant’
Installation failed: Command failed (1)
````

**Comment by hrbrmstr** [comment]
argh. thx. will get docker env setup here for it.

**Comment by hrbrmstr** [comment]
think i got it (local rocker test worked with and without rJava/RJDBC)

**Comment by psychemedia** [comment]
Lovely... works for me too. Thanks:-)
