### ISSUE TITLE
drill_query errors with semicolon completion

### ISSUE THREAD

**Issue by alistaire47** [hrbrmstr/sergeant#8]
Hi! Maybe I just lack experience with SQL APIs, but I find it odd that a query passed to `drill_query` without a terminating semicolon will work but with one will error out:

``` r
library(sergeant)

dc <- drill_connection() 

dc %>% drill_query('SELECT full_name, salary FROM cp.`employee.json` LIMIT 3')
#> # A tibble: 3 x 2
#>         full_name salary
#> *           <chr>  <dbl>
#> 1    Sheri Nowmer  80000
#> 2 Derrick Whelply  40000
#> 3  Michael Spence  40000

dc %>% drill_query('SELECT full_name, salary FROM cp.`employee.json` LIMIT 3;')
#> Query ==> SELECT full_name, salary FROM cp.`employee.json` LIMIT 3;
#> PARSE ERROR: Encountered ";" at line 1, column 57.
#> Was expecting one of:
#>     <EOF> 
#>     "OFFSET" ...
#>     "FETCH" ...
#>     
#> 
#> SQL Query SELECT full_name, salary FROM cp.`employee.json` LIMIT 3;
#>                                                         ^
#> 
#> 
#> [Error Id: a172e1a9-833c-4d89-9b83-de4e250cd1c5 on 192.168.1.3:31010]
```

whereas the Drill shell _only_ works with a semicolon (without it expects a continuation of the query):

```drill
0: jdbc:drill:zk=local> SELECT full_name, salary FROM cp.`employee.json` LIMIT 3;
+--------------------+----------+
|     full_name      |  salary  |
+--------------------+----------+
| Sheri Nowmer       | 80000.0  |
| Derrick Whelply    | 40000.0  |
| Michael Spence     | 40000.0  |
+--------------------+----------+
3 rows selected (0.102 seconds)
```

and when run through the web interface both are fine. 

Looking at `query.r`, the whole query is passed via `httr::POST`, so the error seems to be a product of how the API interprets queries. I'm not sure if this is intended behavior ([the Drill API docs don't use a semicolon](https://drill.apache.org/docs/rest-api/#query), but [the SQL docs do](https://drill.apache.org/docs/lexical-structure/)), but from an R perspective, it seems like a good idea to either

- make note of the restriction/behavior in `?drill_query` or
- add `query <- sub(";$", "", query)` or the like to its code so it works regardless.

Thoughts?

**Comment by hrbrmstr** [comment]
Thx for trying the pkg and taking the time to file an issue! I can def sub
out trailing `;`'s (it's most certainly a REST API issue and not `sergeant`
but I can compensate for it).

**Comment by hrbrmstr** [comment]
I just pushed a version that does the `;` removal. Re-install via GH and
give it a go.

**Comment by alistaire47** [comment]
Wow that was fast! Everything looks great now!
